// Generated by BUCKLESCRIPT VERSION 5.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CanvasComponent$ReactTemplate = require("./CanvasComponent.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, CanvasComponent$ReactTemplate.make(/* array */[])), "page");

/*  Not a pure module */
